### ISSUE TITLE
[Documentation] Create a User Guide for Using the Extension

### ISSUE THREAD

**Issue by atj393** [atj393/promt-save-reuse-chatgpt-and-gemini#10]
### Description:
Create a new `USER_GUIDE.md` file with detailed instructions and screenshots on how to use the extension. Include different scenarios and examples.

### Files Involved:
`USER_GUIDE.md`

### Expected Outcome:
A comprehensive user guide with step-by-step instructions and visuals.

**Comment by Mansi07sharma** [comment]
I want to work on that.

**Comment by atj393** [comment]
@Mansi07sharma Thanks. Assigned to you.

**Comment by atj393** [comment]
@Mansi07sharma are you still interested in working on this topic?

**Comment by arjosephine** [comment]
@atj393 can you assign this to me?

**Comment by atj393** [comment]
@arjosephine Great Wrok. Thanks for your continuous contribution.
