### ISSUE TITLE
[Enhancement] Create a Detailed Setup Guide in `USER_GUIDE.md`

### ISSUE THREAD

**Issue by atj393** [atj393/promt-save-reuse-chatgpt-and-gemini#15]
### Description:
Add a detailed setup guide in `USER_GUIDE.md` with screenshots and step-by-step instructions on how to set up the extension locally. Include how to clone the repo, load the unpacked extension, and test functionalities.

### Files Involved:
`USER_GUIDE.md`

### Expected Outcome:
Users and contributors should have a clear guide to set up and test the extension locally.

**Comment by Mansi07sharma** [comment]
I am interested to work.

**Comment by atj393** [comment]
@Mansi07sharma Thanks. Assigned to you.

**Comment by atj393** [comment]
@Mansi07sharma  are you still interested in working on this topic?

**Comment by Mansi07sharma** [comment]
@atj393 I am interested but I forget before pulling issue that it is not connected with GSSOC so even if I do it ,  I will not get any points on their leaderboard. 

Could you add the level 1 2 or 3?

**Comment by atj393** [comment]
@Mansi07sharma Do you mean GirlScript Summer of Code program?

**Comment by arjosephine** [comment]
@atj393 Can you assign this to me?

**Comment by diya-kishore** [comment]
Kindly assign this to me. very keen to work upon. i promis eto submit the work in a polished manner on time

**Comment by atj393** [comment]
@diya-kishore Sorry, the issues have been already solved in PR #35. 

Please feel free to find something else interesting. Thanks.
