### ISSUE TITLE
[Enhancement] Optimize Event Listener Performance in `content.js`

### ISSUE THREAD

**Issue by atj393** [atj393/promt-save-reuse-chatgpt-and-gemini#16]
### Description:
The `click` and `contextmenu` event listeners are attached to the input fields without debouncing or optimization, leading to potential performance issues. Implement debouncing or throttling to optimize the event handling.

### Files Involved:
`content.js`

### Expected Outcome:
Event listeners should be optimized to avoid redundant executions and improve extension performance.

**Comment by KaranSingh36752** [comment]
can i work on this

**Comment by atj393** [comment]
@KaranSingh36752 Yes, thanks. Assigned to you.

**Comment by KaranSingh36752** [comment]
hey i dm you on discord can you check...

**Comment by atj393** [comment]
@KaranSingh36752  are you still interested in working on this topic?

**Comment by KaranSingh36752** [comment]
@atj393 I made the PR...
You can merge the following request

**Comment by atj393** [comment]
@
