### ISSUE TITLE
[Bug] Fix ChatGPT Integration Issues After Latest Update

### ISSUE THREAD

**Issue by atj393** [atj393/promt-save-reuse-chatgpt-and-gemini#4]
### Description:
The extension is no longer functioning as expected in ChatGPT after the recent update. Investigate the changes in the ChatGPT input field structure and modify the content.js script accordingly.

### Files Involved:
content.js

### Expected Outcome:
Extension should correctly save and retrieve prompts in the new ChatGPT UI.

**Comment by atj393** [comment]
The fix need to applied in the background.js file

`/**
 * Toggles the input storage functionality by either saving the current input field text
 * to local storage or retrieving and inserting saved text into the input field.
 *
 * This function is injected into the active tab and interacts directly with the DOM of the page.
 */
function toggleInputStorage() {
  const inputFieldChatGPT = document.querySelector("#prompt-textarea");
  const inputFieldGemini = document.querySelector(
    '.ql-editor[contenteditable="true"]'
  );
  const inputField = inputFieldChatGPT || inputFieldGemini;
  const url = window.location.href;

  if (!inputField) return;

  if (inputFieldChatGPT && inputField.value.trim()) {
    chrome.storage.local.set({ [url]: inputField.value.trim() }, () => {});
  } else if (inputFieldGemini && inputField.innerText.trim()) {
    chrome.storage.local.set({ [url]: inputField.innerText.trim() }, () => {});
  } else {
    chrome.storage.local.get([url], (result) => {
      if (result[url]) {
        if (inputFieldChatGPT) {
          inputField.value = result[url];
        } else if (inputFieldGemini) {
          inputField.innerHTML = result[url];
        }
      }
    });
  }
}`

**Comment by arjosephine** [comment]
I like to work on this issue.

**Comment by atj393** [comment]
@arjosephine assigned. Thanks.

**Comment by arjosephine** [comment]
@atj393 Please find and review my PR and let me know your thoughts

**Comment by atj393** [comment]
@arjosephine Sure, I will check and update.

**Comment by atj393** [comment]
@arjosephine, Thanks for your contribution to 'Prompt Save & Reuse'
