### ISSUE TITLE
[Bug] Saved Prompts Not Appending Correctly in Gemini

### ISSUE THREAD

**Issue by atj393** [atj393/promt-save-reuse-chatgpt-and-gemini#6]
### Description:
The extension appends saved prompts incorrectly in Gemini, causing the text to be misformatted. Review `appendStoredText()` function to fix HTML formatting issues.

### Files Involved:
`background.js`, `content.js`

### Expected Outcome:
Prompts should append correctly without disrupting the current content.

**Comment by Vaishali785** [comment]
Hey @atj393  I'd like to work on this issue. Could you please assign it to me?

**Comment by atj393** [comment]
@Vaishali785 assigned. Thanks.

**Comment by Vaishali785** [comment]
Hi @atj393, Thanks for assigning this to me. I'm working on this issue but it would be really helpful if you could describe how is it working now(what's the issue) and how should it work. Please attach some screenshot of it.

**Comment by Vaishali785** [comment]
Hey @atj393 , I'm sending you this message because I haven't received any reply from your side on the doubt I had asked some days ago. Please check it and do the needful.

**Comment by atj393** [comment]
@Vaishali785 Thanks for your patience, and sorry for the delay. 

The issue is already solved. Please feel free to take on some other topics if interested. Thanks.
