### ISSUE TITLE
[Enhancement] Add Error Handling for Missing Input Fields

### ISSUE THREAD

**Issue by atj393** [atj393/promt-save-reuse-chatgpt-and-gemini#7]
### Description:
Currently, the extension silently fails when input fields are not found. Add a user notification or console message for better debugging.

### Files Involved:
`background.js`, `content.js`

### Expected Outcome:
Display a message in the console or UI when input fields are not found.

**Comment by DhruvTripathi7877** [comment]
Hey, can you assign this issue to me

**Comment by atj393** [comment]
@DhruvTripathi7877 The error comes from this issue #4

**Comment by om-3004** [comment]
Hello @atj393, Please find and review my PR and let me know if there are any issues.

**Comment by atj393** [comment]
@DhruvTripathi7877 The issue is now fixed. Please take the latest from the main branch.

**Comment by atj393** [comment]
> Hello @atj393, Please find and review my PR and let me know if there are any issues.

@om-3004 I have a added a comment in the PR.

**Comment by DhruvTripathi7877** [comment]
@atj393 Hey actually i was a bit busy in my college today. I saw the PR of this issue of the other person and it was nice so i wanted to ask should i work on some different issue or try to solve this issue from my approach??

**Comment by atj393** [comment]
@DhruvTripathi7877 Sorry, I think its miss communication! Can you please find another issue to contribute? I'll make sure it will not happen again.

**Comment by DhruvTripathi7877** [comment]
I just wanted to clarify can i work on any other issue which is assigned to some other person @atj393

**Comment by atj393** [comment]
@DhruvTripathi7877 Issue number please?

**Comment by DhruvTripathi7877** [comment]
@atj393 16

**Comment by DhruvTripathi7877** [comment]
@atj393 can i work on issue 16??
